# Generated by Django 5.0.2 on 2026-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('BANK_TRANSFER', 'Bank Transfer')], default='ONLINE', max_length=50),
        ),
    ]
