# Generated by Django 5.0.2 on 2026-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_add_prescription_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionverification',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionverification',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionverification',
            name='ocr_confidence',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionverification',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionverification',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescription_verifications/'),
        ),
        migrations.AddField(
            model_name='prescriptionverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
