# Generated by Django 5.0.2 on 2026-02-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_prescriptionverification_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
