from django.core.management.base import BaseCommand
from myapp.models import Service

class Command(BaseCommand):
    help = 'Populate the database with lab test services'

    def handle(self, *args, **options):
        lab_tests = [
            {
                'name': 'Complete Blood Count (CBC)',
                'description': 'Comprehensive blood test that evaluates overall health and detects disorders',
                'category': 'blood',
                'sample_type': 'blood',
                'price': 800,
                'preparation_instructions': 'No special preparation required. Fasting not necessary.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '24 hours',
                'normal_range': 'Varies by parameter',
                'clinical_significance': 'Detects anemia, infection, clotting problems, and other blood disorders',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Hemoglobin',
                'description': 'Measures the amount of hemoglobin in blood',
                'category': 'blood',
                'sample_type': 'blood',
                'price': 300,
                'preparation_instructions': 'No special preparation required.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '6 hours',
                'normal_range': 'Male: 13.5-17.5 g/dL, Female: 12.0-15.5 g/dL',
                'clinical_significance': 'Diagnoses anemia and monitors treatment',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'HbA1c (Glycated Hemoglobin)',
                'description': 'Measures average blood sugar levels over past 2-3 months',
                'category': 'blood',
                'sample_type': 'blood',
                'price': 600,
                'preparation_instructions': 'No special preparation required. Fasting not necessary.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '24 hours',
                'normal_range': '< 5.7%',
                'clinical_significance': 'Diagnoses and monitors diabetes management',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Erythrocyte Sedimentation Rate (ESR)',
                'description': 'Measures inflammation in the body',
                'category': 'blood',
                'sample_type': 'blood',
                'price': 400,
                'preparation_instructions': 'No special preparation required.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '12 hours',
                'normal_range': 'Male: 0-15 mm/hr, Female: 0-20 mm/hr',
                'clinical_significance': 'Detects inflammation and autoimmune diseases',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Lipid Profile',
                'description': 'Comprehensive cholesterol and triglyceride test',
                'category': 'cardiac',
                'sample_type': 'blood',
                'price': 1200,
                'preparation_instructions': 'Fasting required for 12 hours before test.',
                'fasting_required': True,
                'fasting_hours': 12,
                'results_time': '24 hours',
                'normal_range': 'Total Cholesterol: < 200 mg/dL, HDL: > 40 mg/dL, LDL: < 100 mg/dL, Triglycerides: < 150 mg/dL',
                'clinical_significance': 'Assesses cardiovascular risk and monitors heart health',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Total Cholesterol',
                'description': 'Measures total cholesterol levels in blood',
                'category': 'cardiac',
                'sample_type': 'blood',
                'price': 400,
                'preparation_instructions': 'Fasting required for 12 hours.',
                'fasting_required': True,
                'fasting_hours': 12,
                'results_time': '12 hours',
                'normal_range': '< 200 mg/dL',
                'clinical_significance': 'Assesses heart disease risk',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'HDL Cholesterol',
                'description': 'Measures "good" cholesterol levels',
                'category': 'cardiac',
                'sample_type': 'blood',
                'price': 300,
                'preparation_instructions': 'Fasting required for 12 hours.',
                'fasting_required': True,
                'fasting_hours': 12,
                'results_time': '12 hours',
                'normal_range': '> 40 mg/dL',
                'clinical_significance': 'Higher levels are protective against heart disease',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'LDL Cholesterol',
                'description': 'Measures "bad" cholesterol levels',
                'category': 'cardiac',
                'sample_type': 'blood',
                'price': 300,
                'preparation_instructions': 'Fasting required for 12 hours.',
                'fasting_required': True,
                'fasting_hours': 12,
                'results_time': '12 hours',
                'normal_range': '< 100 mg/dL',
                'clinical_significance': 'Lower levels reduce heart disease risk',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Liver Function Test (LFT)',
                'description': 'Comprehensive test for liver health and function',
                'category': 'liver',
                'sample_type': 'blood',
                'price': 1000,
                'preparation_instructions': 'Fasting required for 8-12 hours.',
                'fasting_required': True,
                'fasting_hours': 12,
                'results_time': '24 hours',
                'normal_range': 'Varies by parameter',
                'clinical_significance': 'Detects liver damage, hepatitis, and monitors liver disease',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'SGOT (AST)',
                'description': 'Liver enzyme test for liver damage',
                'category': 'liver',
                'sample_type': 'blood',
                'price': 300,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': 'Male: 10-40 IU/L, Female: 9-32 IU/L',
                'clinical_significance': 'Elevated levels indicate liver damage',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'SGPT (ALT)',
                'description': 'Liver enzyme test for liver cell damage',
                'category': 'liver',
                'sample_type': 'blood',
                'price': 300,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': 'Male: 7-56 IU/L, Female: 5-35 IU/L',
                'clinical_significance': 'Most specific test for liver cell damage',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Bilirubin (Total)',
                'description': 'Measures bilirubin levels in blood',
                'category': 'liver',
                'sample_type': 'blood',
                'price': 250,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': '0.3-1.2 mg/dL',
                'clinical_significance': 'Assesses liver function and detects jaundice',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Kidney Function Test (KFT)',
                'description': 'Comprehensive test for kidney health and function',
                'category': 'kidney',
                'sample_type': 'blood',
                'price': 900,
                'preparation_instructions': 'Fasting required for 8-12 hours.',
                'fasting_required': True,
                'fasting_hours': 12,
                'results_time': '24 hours',
                'normal_range': 'Varies by parameter',
                'clinical_significance': 'Detects kidney damage and monitors kidney disease',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Serum Creatinine',
                'description': 'Measures creatinine levels to assess kidney function',
                'category': 'kidney',
                'sample_type': 'blood',
                'price': 250,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': 'Male: 0.7-1.3 mg/dL, Female: 0.6-1.1 mg/dL',
                'clinical_significance': 'Higher levels indicate kidney dysfunction',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Blood Urea Nitrogen (BUN)',
                'description': 'Measures urea nitrogen levels in blood',
                'category': 'kidney',
                'sample_type': 'blood',
                'price': 250,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': '7-20 mg/dL',
                'clinical_significance': 'Assesses kidney function and protein metabolism',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Thyroid Profile',
                'description': 'Comprehensive thyroid function test (T3, T4, TSH)',
                'category': 'thyroid',
                'sample_type': 'blood',
                'price': 800,
                'preparation_instructions': 'Fasting required for 8-10 hours.',
                'fasting_required': True,
                'fasting_hours': 10,
                'results_time': '24 hours',
                'normal_range': 'TSH: 0.4-4.0 mIU/L, T3: 80-200 ng/dL, T4: 4.5-11.2 µg/dL',
                'clinical_significance': 'Diagnoses thyroid disorders like hypothyroidism and hyperthyroidism',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'TSH (Thyroid Stimulating Hormone)',
                'description': 'Primary test for thyroid function',
                'category': 'thyroid',
                'sample_type': 'blood',
                'price': 350,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': '0.4-4.0 mIU/L',
                'clinical_significance': 'First-line test for thyroid dysfunction',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'T3 (Triiodothyronine)',
                'description': 'Measures active thyroid hormone levels',
                'category': 'thyroid',
                'sample_type': 'blood',
                'price': 300,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': '80-200 ng/dL',
                'clinical_significance': 'Assesses thyroid hormone activity',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'T4 (Thyroxine)',
                'description': 'Measures thyroid hormone levels',
                'category': 'thyroid',
                'sample_type': 'blood',
                'price': 300,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '12 hours',
                'normal_range': '4.5-11.2 µg/dL',
                'clinical_significance': 'Assesses thyroid hormone production',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Vitamin D3',
                'description': 'Measures vitamin D levels in blood',
                'category': 'vitamin',
                'sample_type': 'blood',
                'price': 1200,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '24 hours',
                'normal_range': '30-100 ng/mL',
                'clinical_significance': 'Diagnoses vitamin D deficiency and bone health',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Vitamin B12',
                'description': 'Measures vitamin B12 levels in blood',
                'category': 'vitamin',
                'sample_type': 'blood',
                'price': 800,
                'preparation_instructions': 'No special preparation required.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '24 hours',
                'normal_range': '200-900 pg/mL',
                'clinical_significance': 'Diagnoses B12 deficiency causing anemia and neurological issues',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Urine Routine',
                'description': 'Comprehensive urine analysis for kidney and urinary tract health',
                'category': 'urine',
                'sample_type': 'urine',
                'price': 300,
                'preparation_instructions': 'Collect mid-stream urine sample in sterile container.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '12 hours',
                'normal_range': 'Varies by parameter',
                'clinical_significance': 'Detects urinary tract infections, kidney disease, and metabolic disorders',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Urine Culture',
                'description': 'Identifies bacteria causing urinary tract infections',
                'category': 'urine',
                'sample_type': 'urine',
                'price': 600,
                'preparation_instructions': 'Collect mid-stream urine sample in sterile container.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '48-72 hours',
                'normal_range': 'No bacterial growth',
                'clinical_significance': 'Identifies and guides treatment for UTIs',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Beta HCG',
                'description': 'Pregnancy test to detect human chorionic gonadotropin',
                'category': 'pregnancy',
                'sample_type': 'blood',
                'price': 400,
                'preparation_instructions': 'No special preparation required.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '6 hours',
                'normal_range': 'Non-pregnant: < 5 mIU/mL, Pregnant: > 25 mIU/mL',
                'clinical_significance': 'Confirms pregnancy and monitors early pregnancy',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Double Marker Test',
                'description': 'Prenatal screening for chromosomal abnormalities',
                'category': 'pregnancy',
                'sample_type': 'blood',
                'price': 2500,
                'preparation_instructions': 'Done between 10-13 weeks of pregnancy.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '3-5 days',
                'normal_range': 'Risk assessment based on age and markers',
                'clinical_significance': 'Screens for Down syndrome and other chromosomal abnormalities',
                'home_collection_available': False,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Carcinoembryonic Antigen (CEA)',
                'description': 'Tumor marker for colorectal and other cancers',
                'category': 'cancer',
                'sample_type': 'blood',
                'price': 800,
                'preparation_instructions': 'Fasting required for 8 hours.',
                'fasting_required': True,
                'fasting_hours': 8,
                'results_time': '24 hours',
                'normal_range': '< 3.0 ng/mL',
                'clinical_significance': 'Monitors colorectal cancer treatment and recurrence',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Prostate Specific Antigen (PSA)',
                'description': 'Tumor marker for prostate cancer screening',
                'category': 'cancer',
                'sample_type': 'blood',
                'price': 600,
                'preparation_instructions': 'Avoid ejaculation for 48 hours before test.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '24 hours',
                'normal_range': '< 4.0 ng/mL',
                'clinical_significance': 'Screens for prostate cancer and monitors treatment',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'C-Reactive Protein (CRP)',
                'description': 'Inflammation marker in blood',
                'category': 'infection',
                'sample_type': 'blood',
                'price': 400,
                'preparation_instructions': 'No special preparation required.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '12 hours',
                'normal_range': '< 3.0 mg/L',
                'clinical_significance': 'Detects inflammation and infection',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
            {
                'name': 'Dengue NS1 Antigen',
                'description': 'Early detection test for dengue fever',
                'category': 'infection',
                'sample_type': 'blood',
                'price': 1200,
                'preparation_instructions': 'Test done within first 5 days of fever.',
                'fasting_required': False,
                'fasting_hours': 0,
                'results_time': '6 hours',
                'normal_range': 'Negative',
                'clinical_significance': 'Early diagnosis of dengue infection',
                'home_collection_available': True,
                'lab_collection_available': True,
                'is_active': True,
            },
        ]

        for test_data in lab_tests:
            service, created = Service.objects.get_or_create(
                name=test_data['name'],
                defaults=test_data
            )
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f'Successfully created service: {service.name}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'Service already exists: {service.name}')
                )

        self.stdout.write(
            self.style.SUCCESS(f'Successfully populated {len(lab_tests)} lab test services')
        )
