# Generated by Django 5.0.2 on 2025-12-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_booking_payment_status_userpayment_booking'),
    ]

    operations = [
        # Delete models FIRST (before removing their fields)
        migrations.DeleteModel(
            name='BookingReport',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        # Now remove fields from remaining models
        migrations.RemoveField(
            model_name='userpayment',
            name='booking',
        ),
    ]

